name: First Workflow

on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Welcome message
        run: echo "Welcome to first practice"  

      - name: List
        run: ls

      - name: Display readme
        run: cat README.md
        